# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477956605159b4e2183f2e813520321de274951a4a26eb0c23e2fed88866245486891710cb7f2cdf3515b53a89df7a16dc7d6f56782a250c4aa5205d5f1f6f03

test:
  secret_key_base: 34ab70c4892f4322b260878733fec7409f167970d6ef21d423d9cc1aa2fa088913023dc49cb77d2e43236c417be8bf302278b92c20dcceabbb16c04963dcccd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
