# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
books = Book.create([
                    {title: 'Sherlock', author: 'Arthur Conan Doyle', year:'1892', genre: 'Crime', numberOfPages: '307', description: 'All of the stories within The Adventures of Sherlock Holmes are told in a first-person narrative from the point of view of Dr. Watson, as is the case for all but four of the Sherlock Holmes stories. The Oxford Dictionary of National Biography entry for Doyle suggests that the short stories contained in The Adventures of Sherlock Holmes tend to point out social injustices, such as a kings betrayal of an opera singer, a stepfathers deception of his ward as a fictitious lover, an aristocratic crooks exploitation of a failing pawnbroker, a beggars extensive estate in Kent." It suggests that, in contrast, Holmes is portrayed as offering a fresh and fair approach in an unjust world of "official incompetence and aristocratic privilege". The Adventures of Sherlock Holmes contains many of Doyles favourite Sherlock Holmes stories. In 1927, he submitted a list of what he believed were his twelve best Sherlock Holmes stories to The Strand Magazine. Among those he listed were "The Adventure of the Speckled Band" (as his favourite), "The Red-Headed League" (second), "A Scandal in Bohemia" (fifth) and "The Five Orange Pips" (seventh). The book was banned in the Soviet Union in 1929 because of its alleged "occultism", but the book gained popularity in a black market of similarly banned books, and the restriction was lifted in 1940.', image_url: 'http://dyn4.media.titanbooks.com/products/6192/encounterssherlock.jpg'},
                    {title: 'The Too-Clever Fox', author: 'Leigh Bardugo', year:'2013', genre: 'Novel', numberOfPages: '32', description: "In Ravka, just because you avoid one trap, it doesn't mean you'll escape the next. This story is a companion folk tale to Leigh Bardugo's upcoming novel, Siege and Storm, the second book in the Grisha Trilogy.", image_url: 'https://books.google.pl/books/content?id=sKC8x948r-0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73XRqfP7thajrVUc5yqWB0RV76yYTRnNwuBd8fc3Rf_1dVTDR7ZYCqmDu729_mrgLoTqgqfBDhVHE-Okp7f3pZZLTWuZKkUKUboDuKQZn0Th6uQyNFm_a321PZ1QDkfZD8uKTdj'},
                    {title: 'Little Knife', author: 'Leigh Bardugo', year:'2014', genre: 'Mithology', numberOfPages: '32', description: 'In this third Grisha Trilogy folk tale from Leigh Bardugo, a young girls beauty causes discord in her small town, but her fathers solution may prove far more dangerous. "Little Knife" is a companion story to the third book of the Grisha Trilogy, Ruin and Rising, and the stories "The Witch of Duva" and "The Too-Clever Fox."', image_url: 'https://books.google.com/books/content/images/frontcover/8TlkAwAAQBAJ?fife=w300-rw'},
                    {title: 'A Little Thing Called Life', author: 'Linda Thompson', year:'2016', genre: 'Biography', numberOfPages: '384', description: "Now, for the first time, Linda opens up about it all, telling the full story of her life, loves, and everything in between. From her humble beginnings in Memphis to her nearly five-year relationship with Elvis, she offers an intimate window into their life together, describing how their Southern roots fueled and sustained Graceland’s greatest romance. Going inside their wild stories and tender moments, she paints a portrait of life with the King, as raucous as it is refreshing. But despite the joy they shared, life with Elvis also had darkness, and her account also presents an unsparing look at Elvis’s twin demons—drug abuse and infidelity—forces he battled throughout their time together that would eventually end their relationship just eight months before his untimely death.", image_url: 'https://books.google.com/books/content/images/frontcover/T9y1CgAAQBAJ?fife=w300-rw'},
                    {title: 'M Is for (Data) Monkey', author: 'Ken Puls & Miguel Escobar', year:'2015', genre: 'IT', numberOfPages: '212', description: "Power Query is one component of the Power BI (Business Intelligence) product from Microsoft, and 'M' is the name of the programming language created by it. As more business intelligence pros begin using Power Pivot, they find that they do not have the Excel skills to clean the data in Excel; Power Query solves this problem. This book shows how to use the Power Query tool to get difficult data sets into both Excel and Power Pivot, and is solely devoted to Power Query dashboarding and reporting.", image_url: 'https://books.google.com/books/content/images/frontcover/W4niCgAAQBAJ?fife=w300-rw'},
                    {title: 'Lo Sciamano: Il Risveglio', author: 'VR McCoy', year:'2017', genre: 'Crime', numberOfPages: '157', description: "...storia eccitante che sa cogliere il lato incantevole ma anche quello oscuro delle tradizioni degli Indiani d’America. Cheryl Chatfield, autore di As The Light of Venus Rose. Gli incubi non smettono mai. Fin da bambino ho sempre dovuto lottare per gestirli. Ogni notte si presenta un orrore differente. Li vedo che prendono forma, come se io fossi là. Poi mi risveglio, tutto sudato per quei sogni orribili. Sogno spesso di un altro mondo in cui fuggo, inseguito da strane creature. Creature che possono esistere solo negli incubi, ma che a me appaiono fin troppo reali.", image_url: 'https://books.google.com/books/content/images/frontcover/b-oqDgAAQBAJ?fife=w300-rw'},
                    {title: 'Steal the Show', author: 'Michael Port', year:'2015', genre: 'Business', numberOfPages: '288', description: "Every interaction is a performance, and much of our success—professional and personal—hinges on being able to inspire an audience. And while some people seem to be naturals in the spotlight, this ability very rarely derives from talent alone.", image_url: 'https://books.google.com/books/content/images/frontcover/RzuwBAAAQBAJ?fife=w300-rw'},
                    {title: 'Living Alone and Loving It', author: 'Barbara Feldon', year:'2007', genre: 'Health', numberOfPages: '176', description: "After a relationship impasse, Barbara Feldon -- universally known as the effervescent spy '99' on Get Smart -- found herself living alone. Little did she know that this time would become one of the most enriching and joyous periods of her life.", image_url: 'https://books.google.com/books/content/images/frontcover/U4G-xZ4wRhAC?fife=w300-rw'},
                    {title: 'Moon Over Soho', author: 'Ben Aaronovitch', year:'2011', genre: 'Science-fiction', numberOfPages: '304', description: "The song. That’s what London constable and sorcerer’s apprentice Peter Grant first notices when he examines the corpse of Cyrus Wilkins, part-time jazz drummer and full-time accountant, who dropped dead of a heart attack while playing a gig at Soho’s 606 Club. The notes of the old jazz standard are rising from the body—a sure sign that something about the man’s death was not at all natural but instead supernatural.", image_url: 'https://books.google.com/books/content/images/frontcover/K2FWpeToMH4C?fife=w300-rw'},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''},
                    {title: '', author: '', year:'', genre: '', numberOfPages: '', description: "", image_url: ''}
                    ])
